CC=clang++ 
F=-std=c++11 -Wall 

all: ex241a ex241b ex241c 

ex241a: 
	$(CC) $(F) -o ex241a.out ex2_4_1a.cpp

ex241b:
	$(CC) $(F) -o ex241b.out ex2_4_1b.cpp

ex241c: 
	$(CC) $(F) -o ex241c.out ex2_4_1c.cpp
		
